import { Body, Get, Param, Patch, Post, Query, Req } from '@nestjs/common'; import { ApiOperation } from '@nestjs/swagger'; import { WarehouseController } from '../decorators/warehouse'; import { AdminOnly } from '../decorators/admin-only'; import { AuthRequest } from '../../../collection/auth/interfaces/authRequest.interface'; import { CustomerReturnsService } from '../../../collection/customer-returns/customer-returns.service'; import { CreateCustomerReturnDto, CustomerReturnQueryDto, MapUnclassifiedDto, ReverseCustomerReturnDto, UpdateUnclassifiedDto } from '../../../collection/customer-returns/dtos/customer-returns.dto'; import { ParseIdPipe } from '../../../core/pipes/parseId.pipe'; import { ID } from '../../../core/interfaces/id.interface';
@WarehouseController(['customer-returns'])
export class CustomerReturnsController { constructor(private service:CustomerReturnsService){} private actor(req:AuthRequest){const u:any=req.user,d=u?._doc||u;return String(d?.id||d?._id||'');}
  @Post('preview') @ApiOperation({summary:'Preview a customer return'}) preview(@Body()dto:CreateCustomerReturnDto){return this.service.preview(dto);}
  @Post() @ApiOperation({summary:'Create a customer return transactionally'}) create(@Body()dto:CreateCustomerReturnDto,@Req()req:AuthRequest){return this.service.create(dto,this.actor(req));}
  @Get() findAll(@Query()q:CustomerReturnQueryDto): Promise<any> {return this.service.findAll(q);} @Get('summary') summary(@Query()q:CustomerReturnQueryDto): Promise<any> {return this.service.summary(q);}
  @Post(':id/reverse') @AdminOnly() reverse(@Param('id',ParseIdPipe)id:ID,@Body()dto:ReverseCustomerReturnDto,@Req()req:AuthRequest){return this.service.reverse(String(id),dto.reason,this.actor(req));}
  @Get(':id') findOne(@Param('id',ParseIdPipe)id:ID): Promise<any> {return this.service.findOne(String(id));}
}
@WarehouseController(['trucks'])
export class TruckUnclassifiedReturnStockController { constructor(private service:CustomerReturnsService){} @Get(':truckId/unclassified-return-stock') list(@Param('truckId',ParseIdPipe)id:ID,@Query()q:any): Promise<any> {return this.service.unclassifiedForTruck(String(id),q);} }
@WarehouseController(['unclassified-return-stock'])
export class UnclassifiedReturnStockController { constructor(private service:CustomerReturnsService){} private actor(req:AuthRequest){const u:any=req.user,d=u?._doc||u;return String(d?.id||d?._id||'');} @Patch(':id/map-product') @AdminOnly() map(@Param('id',ParseIdPipe)id:ID,@Body()dto:MapUnclassifiedDto,@Req()req:AuthRequest){return this.service.mapProduct(String(id),dto,this.actor(req));} @Patch(':id') @AdminOnly() update(@Param('id',ParseIdPipe)id:ID,@Body()dto:UpdateUnclassifiedDto){return this.service.updateUnclassified(String(id),dto);} }
