import { BadRequestException, ConflictException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { getConnectionToken, InjectModel } from 'nestjs-typegoose'; import { ReturnModelType } from '@typegoose/typegoose'; import { Connection, Types } from 'mongoose'; import { randomUUID } from 'crypto';
import { CreateCustomerReturnDto, CustomerReturnQueryDto, MapUnclassifiedDto, UpdateUnclassifiedDto } from './dtos/customer-returns.dto';
import { CustomerReturnCounters, CustomerReturns, CustomerReturnStatus, ReturnItemType, TruckUnclassifiedReturnStock, UnclassifiedStatus } from './schemas/customer-returns.schema';
import { Customers } from '../customers/schemas/customers.schema'; import { Trucks } from '../trucks/schemas/trucks.schema'; import { Products } from '../products/schemas/products.schema';
import { InventoryLocationType, InventoryMovements, InventoryMovementType } from '../inventory/schemas/inventory-movement.schema'; import { CustomerDebtLedger, DebtLedgerDirection, DebtLedgerType } from '../debt-payments/schemas/customer-debt-ledger.schema'; import { Notifications, NotificationType } from '../notifications/schemas/notifications.schema';

@Injectable()
export class CustomerReturnsService {
  constructor(@InjectModel(CustomerReturns) private returns: ReturnModelType<typeof CustomerReturns>, @InjectModel(CustomerReturnCounters) private counters: ReturnModelType<typeof CustomerReturnCounters>, @InjectModel(TruckUnclassifiedReturnStock) private unclassified: ReturnModelType<typeof TruckUnclassifiedReturnStock>, @InjectModel(Customers) private customers: ReturnModelType<typeof Customers>, @InjectModel(Trucks) private trucks: ReturnModelType<typeof Trucks>, @InjectModel(Products) private products: ReturnModelType<typeof Products>, @InjectModel(InventoryMovements) private movements: ReturnModelType<typeof InventoryMovements>, @InjectModel(CustomerDebtLedger) private ledger: ReturnModelType<typeof CustomerDebtLedger>, @InjectModel(Notifications) private notifications: ReturnModelType<typeof Notifications>, @Inject(getConnectionToken()) private connection: Connection) {}
  private fail(code: string, message: string) { throw new BadRequestException({ code, message }); }
  private normalized(value: string) { return value.trim().toLocaleLowerCase('vi').normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd').replace(/\s+/g, ' '); }
  private totals(dto: CreateCustomerReturnDto) {
    if (!dto?.items?.length) this.fail('CUSTOMER_RETURN_ITEMS_REQUIRED', 'Phiếu hoàn phải có ít nhất một sản phẩm');
    if (!Types.ObjectId.isValid(dto.customerId) || !Types.ObjectId.isValid(dto.destinationTruckId)) this.fail('CUSTOMER_RETURN_INVALID_REFERENCE', 'Khách hàng hoặc xe không hợp lệ');
    if (!dto.idempotencyKey?.trim()) this.fail('CUSTOMER_RETURN_IDEMPOTENCY_KEY_REQUIRED', 'Thiếu idempotencyKey');
    for (const item of dto.items) {
      if (!!item.productId === !!item.manualProduct) this.fail('CUSTOMER_RETURN_ITEM_TYPE_INVALID', 'Mỗi dòng phải có đúng một productId hoặc manualProduct');
      if (!Number.isInteger(item.qty) || item.qty <= 0) this.fail('CUSTOMER_RETURN_QTY_INVALID', 'Số lượng phải là số nguyên dương');
      if (!Number.isFinite(item.returnUnitPrice) || item.returnUnitPrice < 0 || (item.previousUnitPrice !== undefined && (!Number.isFinite(item.previousUnitPrice) || item.previousUnitPrice < 0))) this.fail('CUSTOMER_RETURN_PRICE_INVALID', 'Giá hoàn không hợp lệ');
      if (item.manualProduct && (!item.manualProduct.name?.trim() || !item.manualProduct.unit?.trim())) this.fail('CUSTOMER_RETURN_MANUAL_PRODUCT_INVALID', 'Sản phẩm ngoài danh mục phải có tên và đơn vị');
    }
    const debtReduction = dto.settlement?.debtReductionAmount;
    if (!Number.isFinite(debtReduction) || debtReduction < 0 || !Array.isArray(dto.settlement?.refunds) || dto.settlement.refunds.some((x) => !['CASH','BANK_TRANSFER'].includes(x.method) || !Number.isFinite(x.amount) || x.amount < 0)) this.fail('CUSTOMER_RETURN_SETTLEMENT_INVALID', 'Phương án xử lý tài chính không hợp lệ');
    const lines = dto.items.map((x) => ({ ...x, lineReturnAmount: x.qty * x.returnUnitPrice, priceDifference: x.previousUnitPrice === undefined ? undefined : (x.returnUnitPrice - x.previousUnitPrice) * x.qty }));
    const returnAmount = lines.reduce((s, x) => s + x.lineReturnAmount, 0), refundAmount = dto.settlement.refunds.reduce((s, x) => s + x.amount, 0);
    if (dto.settlement.debtReductionAmount + refundAmount !== returnAmount) this.fail('CUSTOMER_RETURN_SETTLEMENT_MISMATCH', 'Tổng cấn nợ và hoàn tiền phải bằng giá trị hàng hoàn');
    if (lines.some((x) => x.previousUnitPrice !== undefined && x.previousUnitPrice !== x.returnUnitPrice) && !dto.priceAdjustmentReason?.trim()) this.fail('CUSTOMER_RETURN_PRICE_ADJUSTMENT_REASON_REQUIRED', 'Bắt buộc nhập lý do điều chỉnh giá');
    return { lines, returnAmount, refundAmount, previousReferenceAmount: lines.reduce((s, x) => s + (x.previousUnitPrice === undefined ? 0 : x.previousUnitPrice * x.qty), 0), priceDifferenceAmount: lines.reduce((s, x) => s + (x.priceDifference || 0), 0) };
  }
  async preview(dto: CreateCustomerReturnDto) { return { data: { ...this.totals(dto), settlement: dto.settlement } }; }
  private async nextCode(session: any) { const key = new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Ho_Chi_Minh' }).replaceAll('-', ''); const c: any = await this.counters.findOneAndUpdate({ key }, { $inc: { sequence: 1 } }, { upsert: true, new: true, session }); return `HHT-${key.slice(2)}-${String(c.sequence).padStart(6, '0')}`; }
  async create(dto: CreateCustomerReturnDto, actorId: string) {
    const existing: any = await this.returns.findOne({ idempotencyKey: dto.idempotencyKey }).lean(); if (existing) return { data: existing, idempotent: true };
    const calculated = this.totals(dto), session = await this.connection.startSession(); let result: any;
    try { await session.withTransaction(async () => {
      const [customer, truck]: any[] = await Promise.all([this.customers.findOne({ _id: dto.customerId, isDeleted: false }).session(session), this.trucks.findOne({ _id: dto.destinationTruckId, isDeleted: false, status: 'active' }).session(session)]);
      if (!customer) throw new NotFoundException('Không tìm thấy khách hàng'); if (!truck) throw new NotFoundException('Không tìm thấy xe nhận hàng');
      if (dto.settlement.debtReductionAmount > Number(customer.debt || 0)) this.fail('CUSTOMER_RETURN_DEBT_EXCEEDED', 'Số tiền cấn nợ vượt quá công nợ hiện tại');
      const ids = dto.items.map((x) => x.productId).filter(Boolean); const productRows: any[] = ids.length ? await this.products.find({ _id: { $in: ids }, isDeleted: false }).session(session).lean() : []; const map = new Map(productRows.map((p) => [String(p._id), p])); if (map.size !== new Set(ids).size) this.fail('CUSTOMER_RETURN_PRODUCT_NOT_FOUND', 'Có sản phẩm không tồn tại');
      const code = await this.nextCode(session), returnId = new Types.ObjectId(), items: any[] = [], movementRows: any[] = [];
      for (const line of calculated.lines) { const lineId = randomUUID(); if (line.productId) { const p: any = map.get(line.productId); let inv: any = truck.inventory.find((x: any) => String(x.productId) === line.productId); const before = Number(inv?.qty || 0); if (inv) inv.qty = before + line.qty; else truck.inventory.push({ productId: p._id, qty: line.qty }); items.push({ lineId, itemType: ReturnItemType.CATALOG, productId: String(p._id), productCode: p.code, productName: p.name, unit: p.unit, qty: line.qty, previousUnitPrice: line.previousUnitPrice, returnUnitPrice: line.returnUnitPrice, lineReturnAmount: line.lineReturnAmount, priceDifference: line.priceDifference, condition: line.condition, note: line.note }); movementRows.push({ productId: p._id, type: InventoryMovementType.CUSTOMER_RETURN_TO_TRUCK, quantityChange: line.qty, quantityBefore: before, quantityAfter: before + line.qty, destinationType: InventoryLocationType.TRUCK, destinationTruckId: truck._id, referenceType: 'CUSTOMER_RETURN', referenceId: String(returnId), referenceCode: code, createdBy: actorId, returnQuantity: line.qty, previousUnitPrice: line.previousUnitPrice, returnUnitPrice: line.returnUnitPrice, returnAmount: line.lineReturnAmount }); }
        else { const m = line.manualProduct!; const stock: any = (await this.unclassified.create([{ truckId: String(truck._id), manualCode: m.code?.trim(), name: m.name.trim(), normalizedName: this.normalized(m.name), unit: m.unit.trim(), quantity: line.qty, referenceUnitPrice: line.previousUnitPrice, returnUnitPrice: line.returnUnitPrice, totalReturnValue: line.lineReturnAmount, condition: line.condition, sourceReturnIds: [String(returnId)], status: UnclassifiedStatus.UNCLASSIFIED }], { session }))[0]; items.push({ lineId, itemType: ReturnItemType.MANUAL, manualCode: m.code?.trim(), manualName: m.name.trim(), manualUnit: m.unit.trim(), qty: line.qty, previousUnitPrice: line.previousUnitPrice, returnUnitPrice: line.returnUnitPrice, lineReturnAmount: line.lineReturnAmount, priceDifference: line.priceDifference, condition: line.condition, note: line.note, unclassifiedStockId: String(stock._id) }); } }
      await truck.save({ session }); if (movementRows.length) await this.movements.insertMany(movementRows, { session }); const before = Number(customer.debt || 0), after = before - dto.settlement.debtReductionAmount; customer.debt = after; await customer.save({ session });
      const doc: any = (await this.returns.create([{ _id: returnId, code, idempotencyKey: dto.idempotencyKey, customerId: String(customer._id), customerCode: customer.code, customerName: customer.name, customerPhone: customer.phone, destinationTruckId: String(truck._id), destinationTruckCode: truck.code, destinationTruckName: truck.name, destinationTruckLicensePlate: truck.licensePlate, driverId: truck.driverId && String(truck.driverId), driverName: truck.driverName || truck.driver, items, returnAmount: calculated.returnAmount, previousReferenceAmount: calculated.previousReferenceAmount, priceDifferenceAmount: calculated.priceDifferenceAmount, debtReductionAmount: dto.settlement.debtReductionAmount, refundAmount: calculated.refundAmount, refunds: dto.settlement.refunds, customerDebtBefore: before, customerDebtAfter: after, reason: dto.reason, priceAdjustmentReason: dto.priceAdjustmentReason, note: dto.note, status: CustomerReturnStatus.COMPLETED, createdBy: actorId }], { session }))[0];
      if (dto.settlement.debtReductionAmount) await this.ledger.create([{ customerId: customer._id, customerCode: customer.code, type: DebtLedgerType.CUSTOMER_RETURN_DEBT_REDUCTION, direction: DebtLedgerDirection.DECREASE, amount: dto.settlement.debtReductionAmount, previousDebt: before, decreaseAmount: dto.settlement.debtReductionAmount, balanceAfter: after, occurredAt: new Date(), effectiveAt: new Date(), referenceType: 'CUSTOMER_RETURN', referenceId: String(returnId), referenceCode: code, createdBy: actorId }], { session });
      await this.notifications.create([{ type: NotificationType.CUSTOMER_RETURN_CREATED, title: 'Phiếu hoàn hàng mới', message: `${code} - ${customer.name}`, audience: 'ADMIN', entityType: 'CUSTOMER_RETURN', entityId: String(returnId), entityCode: code }], { session }); result = doc.toObject();
    }); } catch (e: any) { if (e?.code === 11000 && e?.keyPattern?.idempotencyKey) { const doc = await this.returns.findOne({ idempotencyKey: dto.idempotencyKey }).lean(); return { data: doc, idempotent: true }; } throw e; } finally { await session.endSession(); } return { data: result };
  }
  async findAll(q: CustomerReturnQueryDto): Promise<any> { const page = q.page || 1, limit = Math.min(q.limit || 20, 100), filter: any = { isDeleted: false }; if (q.customerId) filter.customerId = q.customerId; if (q.destinationTruckId) filter.destinationTruckId = q.destinationTruckId; if (q.status) filter.status = q.status; const [data,total] = await Promise.all([this.returns.find(filter).sort({createdAt:-1}).skip((page-1)*limit).limit(limit).lean(),this.returns.countDocuments(filter)]); return {data,meta:{page,limit,total,totalPages:Math.ceil(total/limit)}}; }
  async summary(q: CustomerReturnQueryDto) { const filter: any = { isDeleted:false }; if(q.customerId)filter.customerId=q.customerId;if(q.destinationTruckId)filter.destinationTruckId=q.destinationTruckId; const rows:any[]=await this.returns.find(filter).select('status returnAmount debtReductionAmount refundAmount refunds').lean(); const active=rows.filter(x=>x.status===CustomerReturnStatus.COMPLETED); return {data:{totalReturns:active.length,returnAmount:active.reduce((s,x)=>s+x.returnAmount,0),debtReductionAmount:active.reduce((s,x)=>s+x.debtReductionAmount,0),refundAmount:active.reduce((s,x)=>s+x.refundAmount,0)}}; }
  async findOne(id:string): Promise<any> {const doc=await this.returns.findOne({_id:id,isDeleted:false}).lean();if(!doc)throw new NotFoundException('Không tìm thấy phiếu hoàn');return {data:doc};}
  async reverse(id: string, reason: string, actorId: string) { const session=await this.connection.startSession(); let result:any; try { await session.withTransaction(async()=>{ const doc:any=await this.returns.findOne({_id:id,isDeleted:false}).session(session); if(!doc)throw new NotFoundException('Không tìm thấy phiếu hoàn'); if(doc.status===CustomerReturnStatus.REVERSED)throw new ConflictException({code:'CUSTOMER_RETURN_ALREADY_REVERSED',message:'Phiếu đã được đảo'}); const truck:any=await this.trucks.findOne({_id:doc.destinationTruckId,isDeleted:false}).session(session); if(!truck)throw new ConflictException('Xe nhận hàng không còn tồn tại'); const movementRows:any[]=[];
    for(const item of doc.items){ if(item.itemType===ReturnItemType.CATALOG){const inv:any=truck.inventory.find((x:any)=>String(x.productId)===item.productId),before=Number(inv?.qty||0);if(before<item.qty)throw new ConflictException({code:'CUSTOMER_RETURN_STOCK_NOT_ENOUGH',message:`Xe không còn đủ ${item.productName}`});inv.qty=before-item.qty;movementRows.push({productId:item.productId,type:InventoryMovementType.CUSTOMER_RETURN_REVERSED,quantityChange:-item.qty,quantityBefore:before,quantityAfter:before-item.qty,sourceType:InventoryLocationType.TRUCK,sourceTruckId:truck._id,referenceType:'CUSTOMER_RETURN_REVERSAL',referenceId:String(doc._id),referenceCode:doc.code,createdBy:actorId,returnQuantity:item.qty,previousUnitPrice:item.previousUnitPrice,returnUnitPrice:item.returnUnitPrice,returnAmount:item.lineReturnAmount});} else {const stock:any=await this.unclassified.findOne({_id:item.unclassifiedStockId,status:UnclassifiedStatus.UNCLASSIFIED}).session(session);if(!stock||stock.quantity<item.qty)throw new ConflictException({code:'CUSTOMER_RETURN_UNCLASSIFIED_STOCK_CHANGED',message:`Hàng ${item.manualName} đã được phân loại hoặc không còn đủ`});stock.quantity-=item.qty;stock.totalReturnValue=Math.max(0,stock.totalReturnValue-item.lineReturnAmount);if(stock.quantity===0){stock.status=UnclassifiedStatus.DISPOSED;}await stock.save({session});}}
    await truck.save({session});if(movementRows.length)await this.movements.insertMany(movementRows,{session});const customer:any=await this.customers.findOne({_id:doc.customerId,isDeleted:false}).session(session);if(!customer)throw new ConflictException('Khách hàng không còn tồn tại');const before=Number(customer.debt||0),after=before+doc.debtReductionAmount;customer.debt=after;await customer.save({session});if(doc.debtReductionAmount)await this.ledger.create([{customerId:customer._id,customerCode:doc.customerCode,type:DebtLedgerType.CUSTOMER_RETURN_REVERSAL,direction:DebtLedgerDirection.INCREASE,amount:doc.debtReductionAmount,previousDebt:before,increaseAmount:doc.debtReductionAmount,balanceAfter:after,occurredAt:new Date(),effectiveAt:new Date(),referenceType:'CUSTOMER_RETURN_REVERSAL',referenceId:String(doc._id),referenceCode:doc.code,createdBy:actorId,note:reason}],{session});doc.status=CustomerReturnStatus.REVERSED;doc.reversedBy=actorId;doc.reversedAt=new Date();doc.reversalReason=reason;doc.refundRecoveryAmount=doc.refundAmount;doc.refundRecoveryStatus=doc.refundAmount>0?'REQUIRES_COLLECTION':undefined;await doc.save({session});await this.notifications.create([{type:NotificationType.CUSTOMER_RETURN_REVERSED,title:'Đã đảo phiếu hoàn hàng',message:doc.code,audience:'ADMIN',entityType:'CUSTOMER_RETURN',entityId:String(doc._id),entityCode:doc.code}],{session});result=doc.toObject(); });}finally{await session.endSession();}return {data:result,refundRecovery:{amount:result.refundAmount,refunds:result.refunds,status:result.refundRecoveryStatus}}; }
  async unclassifiedForTruck(truckId:string,q:any={}): Promise<any> {const page=Math.max(1,Number(q.page)||1),limit=Math.min(100,Math.max(1,Number(q.limit)||20)),filter:any={truckId,isDeleted:false};if(q.status)filter.status=q.status;const[data,total]=await Promise.all([this.unclassified.find(filter).sort({createdAt:-1}).skip((page-1)*limit).limit(limit).lean(),this.unclassified.countDocuments(filter)]);return{data,meta:{page,limit,total,totalPages:Math.ceil(total/limit)}};}
  async updateUnclassified(id:string,dto:UpdateUnclassifiedDto){if(dto.status===UnclassifiedStatus.MAPPED)this.fail('USE_MAP_PRODUCT_ENDPOINT','Dùng API map-product để phân loại hàng');const set:any={...dto};if(dto.name)set.normalizedName=this.normalized(dto.name);const doc=await this.unclassified.findOneAndUpdate({_id:id,status:UnclassifiedStatus.UNCLASSIFIED,isDeleted:false},{$set:set},{new:true});if(!doc)throw new NotFoundException('Không tìm thấy hàng chờ phân loại');return{data:doc};}
  async mapProduct(id:string,dto:MapUnclassifiedDto,actorId:string){const session=await this.connection.startSession();let result:any;try{await session.withTransaction(async()=>{const stock:any=await this.unclassified.findOne({_id:id,status:UnclassifiedStatus.UNCLASSIFIED,isDeleted:false}).session(session);if(!stock)throw new NotFoundException('Không tìm thấy hàng chờ phân loại');let product:any;if(dto.productId)product=await this.products.findOne({_id:dto.productId,isDeleted:false}).session(session);else{const input=dto.createProduct!;if(await this.products.exists({code:input.code,isDeleted:false}).session(session))throw new ConflictException('Mã sản phẩm đã tồn tại');product=(await this.products.create([{...input,code:input.code.trim().toUpperCase(),costPrice:stock.returnUnitPrice,stock:0}],{session}))[0];}if(!product)throw new NotFoundException('Không tìm thấy sản phẩm');const truck:any=await this.trucks.findOne({_id:stock.truckId,isDeleted:false}).session(session);if(!truck)throw new NotFoundException('Không tìm thấy xe');let inv:any=truck.inventory.find((x:any)=>String(x.productId)===String(product._id));const before=Number(inv?.qty||0);if(inv)inv.qty=before+stock.quantity;else truck.inventory.push({productId:product._id,qty:stock.quantity});await truck.save({session});await this.movements.create([{productId:product._id,type:InventoryMovementType.RETURN_STOCK_CLASSIFIED,quantityChange:stock.quantity,quantityBefore:before,quantityAfter:before+stock.quantity,destinationType:InventoryLocationType.TRUCK,destinationTruckId:truck._id,referenceType:'UNCLASSIFIED_RETURN_STOCK',referenceId:String(stock._id),createdBy:actorId,returnQuantity:stock.quantity,returnUnitPrice:stock.returnUnitPrice,returnAmount:stock.totalReturnValue}],{session});stock.status=UnclassifiedStatus.MAPPED;stock.mappedProductId=String(product._id);await stock.save({session});result=stock.toObject();});}finally{await session.endSession();}return{data:result};}
}
