import { Injectable, NotFoundException } from '@nestjs/common'; import { ReturnModelType } from '@typegoose/typegoose'; import { InjectModel } from 'nestjs-typegoose'; import { AuditLogs } from './schemas/audit-logs.schema'; import { Users } from '../users/schemas/users.schema'; import { AuditLogQueryDto } from './dtos/audit-logs.dto'; import { vietnamDateBoundary } from '../trucks/truck-transfer-date';
@Injectable()
export class AuditLogsService {
  constructor(@InjectModel(AuditLogs) private model: ReturnModelType<typeof AuditLogs>, @InjectModel(Users) private users: ReturnModelType<typeof Users>) {}
  async record(payload: any): Promise<void> { try { let actor: any = null; if (payload.actorId) actor = await this.users.findById(payload.actorId).select('username employeeCode fullName role').lean(); await this.model.create({ ...payload, actorId: actor?._id || payload.actorId || undefined, actorUsername: actor?.username, actorEmployeeCode: actor?.employeeCode, actorFullName: actor?.fullName, actorRole: actor?.role || payload.actorRole, authenticated: Boolean(payload.actorId), occurredAt: payload.occurredAt || new Date() }); } catch (_) { /* Audit failure must never roll back the business request. */ } }
  private filter(query: AuditLogQueryDto) { const filter: any = { isDeleted: false }; for (const field of ['actorId', 'action', 'status', 'resource', 'entityId']) if ((query as any)[field]) filter[field] = (query as any)[field]; if (query.method) filter.method = query.method.toUpperCase(); if (query.search?.trim()) { const escaped = query.search.trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); const regex = { $regex: escaped, $options: 'i' }; filter.$or = ['correlationId', 'actorUsername', 'actorEmployeeCode', 'actorFullName', 'path', 'resource', 'entityId', 'entityCode', 'description', 'errorMessage'].map((field) => ({ [field]: regex })); } if (query.from || query.to) { filter.occurredAt = {}; if (query.from) filter.occurredAt.$gte = vietnamDateBoundary(query.from, false); if (query.to) filter.occurredAt.$lte = vietnamDateBoundary(query.to, true); } return filter; }
  async findAll(query: AuditLogQueryDto): Promise<any> { const page = Number(query.page) || 1, limit = Number(query.limit) || 20, filter = this.filter(query); const [data, total] = await Promise.all([this.model.find(filter).select('-requestBody -responseBody -errorDetails').sort({ occurredAt: -1, createdAt: -1, _id: -1 }).skip((page - 1) * limit).limit(limit).lean(), this.model.countDocuments(filter)]); return { data, meta: { page, limit, total, totalPages: Math.ceil(total / limit) } }; }
  async findOne(id: string): Promise<any> { const data = await this.model.findOne({ _id: id, isDeleted: false }).lean(); if (!data) throw new NotFoundException('Không tìm thấy nhật ký hoạt động'); return { data }; }
  async summary(query: AuditLogQueryDto): Promise<any> { const filter = this.filter(query); const [total, failed, actors, actions] = await Promise.all([this.model.countDocuments(filter), this.model.countDocuments({ ...filter, status: 'FAILED' }), this.model.distinct('actorId', { ...filter, actorId: { $ne: null } }), this.model.aggregate([{ $match: filter }, { $group: { _id: '$action', count: { $sum: 1 } } }, { $sort: { count: -1 } }])]); return { data: { totalActivities: total, failedActivities: failed, successfulActivities: total - failed, uniqueActors: actors.length, actions: actions.map((item) => ({ action: item._id, count: item.count })) } }; }
}
