import { BadRequestException } from '@nestjs/common'; import { DashboardPeriodQueryDto, ReportGranularity, ReportPeriodType } from './dtos/dashboard.dto'; import { vietnamDateBoundary } from '../trucks/truck-transfer-date';
export function resolveReportPeriod(query: DashboardPeriodQueryDto) {
  if (query.timezone && query.timezone !== 'Asia/Ho_Chi_Minh') throw new BadRequestException('Hệ thống hiện chỉ hỗ trợ timezone Asia/Ho_Chi_Minh');
  const nowLocal = new Date(Date.now() + 25200000); const anchorText = query.anchor || `${nowLocal.getUTCFullYear()}-${String(nowLocal.getUTCMonth() + 1).padStart(2, '0')}-${String(nowLocal.getUTCDate()).padStart(2, '0')}`; const anchor = new Date(`${anchorText}T12:00:00+07:00`); if (Number.isNaN(+anchor)) throw new BadRequestException('Ngày tham chiếu không hợp lệ'); const type = query.period || (query.from || query.to ? ReportPeriodType.CUSTOM : ReportPeriodType.MONTH);
  let fromText = query.from, toText = query.to; const local = new Date(anchor.getTime() + 25200000); const y = local.getUTCFullYear(), m = local.getUTCMonth(), d = local.getUTCDate(); const fmt = (date: Date) => `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, '0')}-${String(date.getUTCDate()).padStart(2, '0')}`;
  if (type !== ReportPeriodType.CUSTOM) { let start: Date, end: Date; if (type === ReportPeriodType.WEEK) { const weekday = local.getUTCDay() || 7; start = new Date(Date.UTC(y, m, d - weekday + 1)); end = new Date(Date.UTC(y, m, d - weekday + 7)); } else if (type === ReportPeriodType.MONTH) { start = new Date(Date.UTC(y, m, 1)); end = new Date(Date.UTC(y, m + 1, 0)); } else if (type === ReportPeriodType.QUARTER) { const qm = Math.floor(m / 3) * 3; start = new Date(Date.UTC(y, qm, 1)); end = new Date(Date.UTC(y, qm + 3, 0)); } else { start = new Date(Date.UTC(y, 0, 1)); end = new Date(Date.UTC(y, 12, 0)); } fromText = fmt(start); toText = fmt(end); }
  if (!fromText || !toText) throw new BadRequestException('Khoảng báo cáo tùy chỉnh cần from và to'); const from = vietnamDateBoundary(fromText, false), to = vietnamDateBoundary(toText, true); if (from > to) throw new BadRequestException('Ngày bắt đầu phải trước ngày kết thúc'); const duration = to.getTime() - from.getTime() + 1; const previousTo = new Date(from.getTime() - 1), previousFrom = new Date(previousTo.getTime() - duration + 1); const days = duration / 86400000; const granularity = query.granularity || (type === ReportPeriodType.WEEK || days <= 31 ? ReportGranularity.DAY : days <= 180 ? ReportGranularity.WEEK : ReportGranularity.MONTH);
  return { type, from, to, compareFrom: previousFrom, compareTo: previousTo, timezone: 'Asia/Ho_Chi_Minh', granularity };
}
