import { BadRequestException, ConflictException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { ReturnModelType } from '@typegoose/typegoose'; import { getConnectionToken, InjectModel } from 'nestjs-typegoose'; import { Connection, Types } from 'mongoose';
import { DebtPaymentCounters, DebtPayments, DebtPaymentStatus } from './schemas/debt-payments.schema'; import { CancelDebtPaymentDto, CreateDebtPaymentDto, DebtPaymentQueryDto } from './dtos/debt-payments.dto';
import { Customers } from '../customers/schemas/customers.schema'; import { Invoices, InvoicePaymentStatus, PaymentMethod } from '../invoices/schemas/invoices.schema'; import { vietnamDateBoundary } from '../trucks/truck-transfer-date';
import { CustomerDebtLedger, DebtLedgerDirection, DebtLedgerType } from './schemas/customer-debt-ledger.schema';
@Injectable()
export class DebtPaymentsService {
  constructor(@InjectModel(DebtPayments) private model: ReturnModelType<typeof DebtPayments>, @InjectModel(DebtPaymentCounters) private counter: ReturnModelType<typeof DebtPaymentCounters>, @InjectModel(Customers) private customers: ReturnModelType<typeof Customers>, @InjectModel(Invoices) private invoices: ReturnModelType<typeof Invoices>, @InjectModel(CustomerDebtLedger) private ledger: ReturnModelType<typeof CustomerDebtLedger>, @Inject(getConnectionToken()) private connection: Connection) {}
  private dateKey(date: Date) { const value = new Date(date.getTime() + 25200000); return `${String(value.getUTCFullYear()).slice(2)}${String(value.getUTCMonth() + 1).padStart(2, '0')}${String(value.getUTCDate()).padStart(2, '0')}`; }
  private normalizePayments(payments: any[]) { const map = new Map<PaymentMethod, any>(); for (const payment of payments || []) { const amount = Number(payment.amount); if (!Object.values(PaymentMethod).includes(payment.method) || !Number.isFinite(amount) || amount <= 0) throw new BadRequestException('Thông tin thanh toán không hợp lệ'); const previous = map.get(payment.method); map.set(payment.method, previous ? { ...previous, amount: previous.amount + amount, referenceCode: payment.referenceCode || previous.referenceCode } : { ...payment, amount }); } const rows = [...map.values()]; if (!rows.length) throw new BadRequestException('Phiếu thu phải có ít nhất một khoản thanh toán'); return rows; }
  async create(customerId: string, dto: CreateDebtPaymentDto, actorId?: string): Promise<any> {
    if (!Types.ObjectId.isValid(customerId)) throw new BadRequestException('Khách hàng không hợp lệ'); const date = dto.date ? new Date(dto.date) : new Date(); if (Number.isNaN(+date)) throw new BadRequestException('Ngày phiếu thu không hợp lệ'); const payments = this.normalizePayments(dto.payments); const amount = payments.reduce((sum, row) => sum + row.amount, 0);
    const session = await this.connection.startSession(); let response: any;
    try { await session.withTransaction(async () => {
      const customerBefore: any = await this.customers.findOne({ _id: customerId, isDeleted: false }).session(session).lean(); if (!customerBefore) throw new NotFoundException('Không tìm thấy khách hàng');
      const selectedIds = [...new Set(dto.invoiceIds || [])]; const invoiceFilter: any = { customerId, debtAmount: { $gt: 0 }, isDeleted: false }; if (selectedIds.length) invoiceFilter._id = { $in: selectedIds };
      const invoices: any[] = await this.invoices.find(invoiceFilter).sort({ date: 1, _id: 1 }).session(session).lean(); if (selectedIds.length && invoices.length !== selectedIds.length) throw new BadRequestException('Một hoặc nhiều hóa đơn không còn công nợ hoặc không thuộc khách hàng');
      const allocatable = invoices.reduce((sum, invoice) => sum + Number(invoice.debtAmount || 0), 0); if (amount > allocatable) throw new ConflictException({ code: 'DEBT_PAYMENT_EXCEEDS_ALLOCATABLE_DEBT', message: 'Số tiền thanh toán vượt công nợ của các hóa đơn được chọn' });
      const customerAfter: any = await this.customers.findOneAndUpdate({ _id: customerId, isDeleted: false, debt: { $gte: amount } }, { $inc: { debt: -amount } }, { new: true, session }); if (!customerAfter) throw new ConflictException({ code: 'DEBT_PAYMENT_EXCEEDS_CUSTOMER_DEBT', message: 'Số tiền thanh toán vượt công nợ hiện tại' });
      const day = this.dateKey(date); const sequence: any = await this.counter.findOneAndUpdate({ key: `DEBT_PAYMENT_${day}` }, { $inc: { sequence: 1 } }, { upsert: true, new: true, session }); const code = `PTCN-${day}-${String(sequence.sequence).padStart(6, '0')}`; const receiptId = new Types.ObjectId();
      let remaining = amount; const allocations: any[] = [];
      for (const invoice of invoices) { if (remaining <= 0) break; const debtBefore = Number(invoice.debtAmount || 0); const allocated = Math.min(remaining, debtBefore); const debtAfter = debtBefore - allocated; const paidAfter = Number(invoice.paidAmount || 0) + allocated; const updated = await this.invoices.updateOne({ _id: invoice._id, debtAmount: debtBefore, isDeleted: false }, { $set: { debtAmount: debtAfter, paidAmount: paidAfter, paymentStatus: debtAfter === 0 ? InvoicePaymentStatus.PAID : InvoicePaymentStatus.PARTIAL }, $push: { debtPayments: { receiptId: String(receiptId), receiptCode: code, amount: allocated, paidAt: date } } }, { session }); if (updated.modifiedCount !== 1) throw new ConflictException('Công nợ hóa đơn vừa thay đổi, vui lòng thử lại'); allocations.push({ invoiceId: invoice._id, invoiceCode: invoice.code, amount: allocated, debtBefore, debtAfter }); remaining -= allocated; }
      if (remaining !== 0) throw new ConflictException('Không thể phân bổ hết số tiền thanh toán');
      const receipt: any = (await this.model.create([{ _id: receiptId, code, date, customerId: customerBefore._id, customerCode: customerBefore.code, customerName: customerBefore.name, customerPhone: customerBefore.phone, amount, payments, allocations, customerDebtBefore: customerBefore.debt, customerDebtAfter: customerAfter.debt, note: dto.note?.trim(), createdBy: actorId || undefined }], { session }))[0]; response = { data: receipt };
      await this.ledger.create([{ customerId: customerBefore._id, customerCode: customerBefore.code, type: DebtLedgerType.DEBT_PAYMENT, direction: DebtLedgerDirection.DECREASE, amount, balanceAfter: customerAfter.debt, occurredAt: date, referenceCode: code, debtPaymentId: receiptId, createdBy: actorId }], { session });
    }); return response; } finally { await session.endSession(); }
  }
  private filter(query: DebtPaymentQueryDto) { const filter: any = { isDeleted: false }; if (query.customerId) filter.customerId = query.customerId; if (query.status) filter.status = query.status; if (query.search?.trim()) { const escaped = query.search.trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); const regex = { $regex: escaped, $options: 'i' }; filter.$or = [{ code: regex }, { customerCode: regex }, { customerName: regex }, { customerPhone: regex }, { 'allocations.invoiceCode': regex }]; } if (query.from || query.to) { filter.date = {}; if (query.from) filter.date.$gte = vietnamDateBoundary(query.from, false); if (query.to) filter.date.$lte = vietnamDateBoundary(query.to, true); } return filter; }
  async findAll(query: DebtPaymentQueryDto): Promise<any> { const page = Number(query.page) || 1, limit = Number(query.limit) || 20, filter = this.filter(query); const [data, total] = await Promise.all([this.model.find(filter).sort({ date: -1, createdAt: -1, _id: -1 }).skip((page - 1) * limit).limit(limit).lean(), this.model.countDocuments(filter)]); return { data, meta: { page, limit, total, totalPages: Math.ceil(total / limit) } }; }
  async findOne(id: string): Promise<any> { const data = await this.model.findOne({ _id: id, isDeleted: false }).lean(); if (!data) throw new NotFoundException('Không tìm thấy phiếu thu công nợ'); return { data }; }
  async cancel(id: string, dto: CancelDebtPaymentDto, actorId?: string): Promise<any> {
    if (!dto.reason?.trim()) throw new BadRequestException('Phải nhập lý do hủy phiếu thu'); const session = await this.connection.startSession(); let response: any;
    try { await session.withTransaction(async () => { const now = new Date(); const receipt: any = await this.model.findOneAndUpdate({ _id: id, status: DebtPaymentStatus.ACTIVE, isDeleted: false }, { status: DebtPaymentStatus.CANCELLED, cancelledBy: actorId || undefined, cancelledAt: now, cancelReason: dto.reason.trim() }, { new: true, session }); if (!receipt) throw new ConflictException('Phiếu thu không tồn tại hoặc đã được hủy'); const customer: any = await this.customers.findOneAndUpdate({ _id: receipt.customerId, isDeleted: false }, { $inc: { debt: receipt.amount } }, { new: true, session }); if (!customer) throw new ConflictException('Không thể khôi phục công nợ khách hàng'); for (const allocation of receipt.allocations) { const invoice: any = await this.invoices.findOne({ _id: allocation.invoiceId, paidAmount: { $gte: allocation.amount }, isDeleted: false }).session(session).lean(); if (!invoice) throw new ConflictException('Không thể khôi phục công nợ hóa đơn'); const paidAmount = Number(invoice.paidAmount) - allocation.amount; const debtAmount = Number(invoice.debtAmount) + allocation.amount; await this.invoices.updateOne({ _id: invoice._id }, { $set: { paidAmount, debtAmount, paymentStatus: paidAmount === 0 ? InvoicePaymentStatus.UNPAID : InvoicePaymentStatus.PARTIAL }, $pull: { debtPayments: { receiptId: String(receipt._id) } } }, { session }); } await this.ledger.create([{ customerId: receipt.customerId, customerCode: receipt.customerCode, type: DebtLedgerType.DEBT_PAYMENT_CANCELLED, direction: DebtLedgerDirection.INCREASE, amount: receipt.amount, balanceAfter: customer.debt, occurredAt: now, referenceCode: receipt.code, debtPaymentId: receipt._id, createdBy: actorId, note: dto.reason.trim() }], { session }); response = { data: receipt }; }); return response; } finally { await session.endSession(); }
  }
}
